repos:
-   repo: 'https://github.com/pre-commit/mirrors-clang-format'
    rev: v14.0.6
    hooks:
      - id: clang-format
        types_or:
          - javascript
          - c++
          - c
          - cuda
        files: '\.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto|js|ts)$'
